version: '3'
services:
  frontend:
    build: ./FRONTEND
    ports:
      - "8001:8001"
    networks:
      - app-network

  backend:
    build: ./SERVER
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

